/** 西乡路口、广深路北边，能反复筛的地点 */
export const PLACES = [
  {
    id: "pingluan",
    name: "平峦山公园",
    kind: "山 · 林",
    vibe: "nature",
    far: false,
    overpassBike: false,
    shade: true,
    crowded: "low",
    how: "前进二路宝田三路。西乡盐田大门坐 M350 / M210 约 5 站，或沿前进二路骑 20–30 分钟。不用过广深天桥。",
    why: "西乡北边最像样的自然地。林荫多，山顶能看铁岗水库。",
  },
  {
    id: "tiegang",
    name: "铁岗水库大坝",
    kind: "湖",
    vibe: "nature",
    far: false,
    overpassBike: false,
    shade: false,
    crowded: "low",
    how: "12 号线宝田一路转 B834 到铁岗水库西门。门口登记。自行车不能骑进去。",
    why: "真的是湖，平、安静，大约 1.5 公里。比西乡河边更像自然。",
  },
  {
    id: "qilong",
    name: "企龙山公园",
    kind: "山",
    vibe: "nature",
    far: false,
    overpassBike: false,
    shade: true,
    crowded: "low",
    how: "平峦山和铁岗之间。热天坐车到门口再走，大约半小时到顶。",
    why: "更小、更安静，人少。",
  },
  {
    id: "xixiang-river",
    name: "西乡河碧道（往北）",
    kind: "河边",
    vibe: "nature",
    far: false,
    overpassBike: false,
    shade: true,
    crowded: "low",
    how: "从西乡路口沿河往铁岗方向。家门口那段偏城市河，越往北越像自然。",
    why: "最近。有演唱会、不想走远时可以散一圈。",
  },
  {
    id: "tiezai",
    name: "铁仔山公园",
    kind: "山 · 海",
    vibe: "nature",
    far: false,
    overpassBike: true,
    shade: false,
    crowded: "mid",
    how: "西乡立交、广深公路西侧。热天推自行车上天桥会累。",
    why: "能看海和日落。路可能要过广深。",
  },
  {
    id: "imax",
    name: "大仟里 IMAX",
    kind: "电影",
    vibe: "city",
    far: false,
    overpassBike: false,
    shade: true,
    crowded: "mid",
    how: "坪洲 / 西乡步行街附近。商场本身不当逛的，只买一场票。",
    why: "场次定了就出门。近。",
  },
  {
    id: "old-street",
    name: "西乡步行街 · 北帝古庙",
    kind: "老街",
    vibe: "city",
    far: false,
    overpassBike: false,
    shade: true,
    crowded: "mid",
    how: "西乡路口走路能到。真理街、巡抚街可以串着走。",
    why: "烟火，不是海景。现在比以前冷清。",
  },
  {
    id: "baoan-park",
    name: "宝安公园",
    kind: "公园",
    vibe: "nature",
    far: false,
    overpassBike: false,
    shade: true,
    crowded: "mid",
    how: "地铁 5 号线洪浪北或 12 号线上川。有湖、绿道、小山。",
    why: "城市公园，比商场像出门，比平峦山更近市区。",
  },
  {
    id: "yantian",
    name: "盐田街夜市",
    kind: "夜市",
    vibe: "city",
    far: false,
    overpassBike: false,
    shade: false,
    crowded: "high",
    how: "1 号线西乡站附近。下午四点后才有。周末人多。",
    why: "近，能吃能逛。容易塞。",
  },
  {
    id: "xibay",
    name: "西湾红树林",
    kind: "海",
    vibe: "nature",
    far: true,
    overpassBike: true,
    shade: false,
    crowded: "mid",
    how: "骑行会觉得远。日落看过了；再去要有别的事，热天别推车上桥。",
    why: "海边。近的都划掉以后再拿出来。",
  },
  {
    id: "lixinhu",
    name: "立新湖公园",
    kind: "湖",
    vibe: "nature",
    far: true,
    overpassBike: false,
    shade: true,
    crowded: "low",
    how: "从西乡路口大约 1 小时交通。环湖绿道。",
    why: "湖景安静。近的不够用时才推荐。",
  },
];

export const SOURCES = [
  {
    id: "weekend",
    name: "深圳周末去哪玩",
    kind: "公众号",
    use: "微信搜索后回复「周末」或「每日活动」。演出、展览、免费活动汇总。",
    open: "weixin://",
    web: "https://mp.weixin.qq.com/",
    searchHint: "微信搜索：深圳周末去哪玩",
  },
  {
    id: "bendibao",
    name: "深圳本地宝",
    kind: "网站",
    use: "本周末活动汇总，常更新演出和展会。",
    web: "http://sz.bendibao.com/xiuxian/2025213/984876.htm",
  },
  {
    id: "damai",
    name: "大麦",
    kind: "票务",
    use: "演唱会、展览、体育。心愿里的艺人优先在这里查在售。",
    web: "https://m.damai.cn/shows/home.html",
  },
  {
    id: "showstart",
    name: "秀动",
    kind: "票务",
    use: "Livehouse、独立演出。宝安沙井梦田这类小现场也在这。",
    web: "https://www.showstart.com/",
  },
  {
    id: "baoan",
    name: "滨海宝安 / 宝安发布",
    kind: "公众号",
    use: "宝安区活动、灯光秀、图书馆和公园通知。",
    searchHint: "微信搜索：滨海宝安 或 宝安发布",
    web: "https://mp.weixin.qq.com/",
  },
];

export const WISH_SEARCH = {
  damai: (q) => `https://search.damai.cn/search.html?keyword=${encodeURIComponent(q)}`,
  showstart: (q) => `https://www.showstart.com/home/search?keyword=${encodeURIComponent(q)}`,
  weibo: (q) => `https://s.weibo.com/weibo?q=${encodeURIComponent(q + " 演唱会")}`,
};

/** 2026-09-07 检索快照，打开心愿时先给结论，再给可点的源 */
export const SEEDED_WISHES = [
  {
    id: "liuxijun",
    text: "听刘惜君的现场",
    keyword: "刘惜君",
    checkedAt: "2026-09-07",
    status: "none",
    note: "大麦搜索没有在售个唱。《歌手 2026》已于 7 月结束。找票网一类第三方「订票」页是空壳，不要点。有官宣再从大麦 / 秀动进。",
  },
];
